### ISSUE TITLE
Add proper types to support .d.ts generation

### ISSUE THREAD

**Issue by PWKad** [aurelia/validatejs#10]
Make sure all of the types match results.

**Comment by Roustalski** [comment]
Howdy,

I'd like to assist here, but I need some pointers on what I need to do to get them generated. I'm assuming we aren't creating the *.d.ts file by hand.

Thanks.

**Comment by PWKad** [comment]
Awesome!

So we add types just like in TypeScript and we use those to generate typedocs from.  Then, when actually building, we strip those types so they don't linger around in the browser at runtime.

[Here is an example of adding types to methods](https://github.com/aurelia/validation/commit/43c4538dc452e55b389c48bd50cf6349fc731f98)

[Here is an example of adding typedoc comments to methods](https://github.com/aurelia/validation/blob/0.6.6/src/validation-group.js#L12-L35)

You can test the output using `gulp doc-generate` from [here](https://github.com/aurelia/validation/blob/master/build/tasks/doc.js#L6-L20)

**Comment by PWKad** [comment]
By the way this should go without saying but I'm going to say it anyway - this will be an awesome contribution and we appreciate the help a ton!

**Comment by da1z** [comment]
Hi. I want to do it but have a problem on start.
I have cloned the repo and when i am running gulp doc-generate i am getting some errors:
`[11:41:41] C:/Projects/validatejs/dist/aurelia-validatejs.d.ts(3)
 Cannot find module 'aurelia-pal'.
[11:41:41] C:/Projects/validatejs/dist/aurelia-validatejs.d.ts(6)
 Cannot find module 'aurelia-validation'.
[11:41:41] C:/Projects/validatejs/dist/aurelia-validatejs.d.ts(9)
 Cannot find module 'aurelia-dependency-injection'.
[11:41:41] C:/Projects/validatejs/dist/aurelia-validatejs.d.ts(12)
 Cannot find module 'aurelia-metadata'.
[11:41:41] C:/Projects/validatejs/dist/aurelia-validatejs.d.ts(13)
 Cannot find module 'validate.js'.
[11:41:41] 'doc-generate' errored after 2.58 s
[11:41:41] Error in plugin 'gulp-typedoc'
Message:
    Failed to generate load TypeDoc project.`

What am i doing wrong?

**Comment by y2k4life** [comment]
I'm new to this, but would like to help. If just by stating my opinion and asking questions.

Just as issue #67 was being closed I was posting an update. But I would assume in this case a .d.ts file is already created specifically aurelia-validatejs.d.ts. The issue you are getting is because of error with that file, see my comments on #67. It also looks not to be specific to webpack.

To me the `gulp doc-generate` is not needed if the .d.ts file is already created. My question, now that aurelia-validatejs.d.ts is there what are the maintenance of the file moving forward? The idea of adding types to a .js file, generate docs, then remove them seems odd for maintaining the file. Would we just maintain the .d.ts file now? Is the `gulp doc-generate` suggestion a starting point? When maintaining other .d.ts files do you go through that exercises of adding types .js files and removing them?

As I pointed out in #67 is using the type `any` for all things a good solution?

I also understand that once this a .d.ts is built and is set in stone the signature of methods don't change that much and objects types are not added often. Therefore not too many changes to the .d.ts files are needed. Once you get it right from the start there should not be too many changes moving forward.

**Comment by derkork** [comment]
I have started a branch for adding docs and type hints here: 

https://github.com/derkork/validatejs/tree/issue-10/src

I'm not really sure about the property observer (https://github.com/derkork/validatejs/blob/issue-10/src/property-observer.js) from the code this does return nothing, but other functions are calling this and they seem to expect some return type.

I'm also getting the documentation generation error that @da1z got, so I can't create the documentation here locally.

**Comment by jdanyow** [comment]
d.ts generation is implemented in the alpha 
http://blog.durandal.io/2016/06/14/new-validation-alpha-is-here/

**Comment by EisenbergEffect** [comment]
Closing since this has been setup.
